CC=arm-none-eabi-gcc
MACH=cortex-m4
CFLAGS= -c -mcpu=$(MACH) -mthumb -std=gnu11 -O0 

all:main.o startup.o
	
main.o:main.c
	arm-none-eabi-gcc $(CFLAGS) main.c -o main.o

startup.o: startup.c
	$(CC) $(CFLAGS) -o $@ $^
	
clean:
	rm -rf *.o *.elf
	
	